
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "COMMENT DIV ID LPAREN MINUS MULT NUMBER PLUS RPAREN\n        stmt : expr\n    \n        expr : expr PLUS term\n             | expr MINUS term \n             | term \n     \n        term : term MULT factor\n             | term DIV factor \n             | factor\n     \n        factor : ID \n               | '(' expr ')'             \n    "
    
_lr_action_items = {'ID':([0,6,7,8,9,10,],[5,5,5,5,5,5,]),'(':([0,6,7,8,9,10,],[6,6,6,6,6,6,]),'$end':([1,2,3,4,5,12,13,14,15,16,],[0,-1,-4,-7,-8,-2,-3,-5,-6,-9,]),'PLUS':([2,3,4,5,11,12,13,14,15,16,],[7,-4,-7,-8,7,-2,-3,-5,-6,-9,]),'MINUS':([2,3,4,5,11,12,13,14,15,16,],[8,-4,-7,-8,8,-2,-3,-5,-6,-9,]),')':([3,4,5,11,12,13,14,15,16,],[-4,-7,-8,16,-2,-3,-5,-6,-9,]),'MULT':([3,4,5,12,13,14,15,16,],[9,-7,-8,9,9,-5,-6,-9,]),'DIV':([3,4,5,12,13,14,15,16,],[10,-7,-8,10,10,-5,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stmt':([0,],[1,]),'expr':([0,6,],[2,11,]),'term':([0,6,7,8,],[3,3,12,13,]),'factor':([0,6,7,8,9,10,],[4,4,4,4,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stmt","S'",1,None,None,None),
  ('stmt -> expr','stmt',1,'p_stmt','parser_test.py',84),
  ('expr -> expr PLUS term','expr',3,'p_expr','parser_test.py',90),
  ('expr -> expr MINUS term','expr',3,'p_expr','parser_test.py',91),
  ('expr -> term','expr',1,'p_expr','parser_test.py',92),
  ('term -> term MULT factor','term',3,'p_term','parser_test.py',100),
  ('term -> term DIV factor','term',3,'p_term','parser_test.py',101),
  ('term -> factor','term',1,'p_term','parser_test.py',102),
  ('factor -> ID','factor',1,'p_factor','parser_test.py',110),
  ('factor -> ( expr )','factor',3,'p_factor','parser_test.py',111),
]
